language: python
dist: xenial
matrix:
  include:
    - python: "3.6"
    - python: "3.7"

branches:
  only:
    - master

before_script:
  - pip install tox pipenv

script:
  - tox --skip-missing-interpreters
